USE [master]
GO
/****** Object:  Database [Doorway]    Script Date: 05/13/2019 12:39:52 ******/
CREATE DATABASE [Doorway]  
GO
ALTER DATABASE [Doorway] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Doorway].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Doorway] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Doorway] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Doorway] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Doorway] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Doorway] SET ARITHABORT OFF
GO
ALTER DATABASE [Doorway] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Doorway] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Doorway] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Doorway] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Doorway] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Doorway] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Doorway] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Doorway] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Doorway] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Doorway] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Doorway] SET  DISABLE_BROKER
GO
ALTER DATABASE [Doorway] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Doorway] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Doorway] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Doorway] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Doorway] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Doorway] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Doorway] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Doorway] SET  READ_WRITE
GO
ALTER DATABASE [Doorway] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Doorway] SET  MULTI_USER
GO
ALTER DATABASE [Doorway] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Doorway] SET DB_CHAINING OFF
GO
USE [Doorway]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 05/13/2019 12:39:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Color] [nvarchar](6) NULL,
	[ContributeToWorktime] [tinyint] NULL,
	[CreatedOn] [datetime] NOT NULL,
	[UpdatedOn] [datetime] NULL,
	[DeletedOn] [datetime] NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 05/13/2019 12:39:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Login] [nvarchar](50) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Picture] [varbinary](max) NULL,
	[CreatedOn] [datetime] NOT NULL,
	[UpdatedOn] [datetime] NULL,
	[DeletedOn] [datetime] NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Events]    Script Date: 05/13/2019 12:39:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Events](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[StartAt] [datetime] NOT NULL,
	[EndAt] [datetime] NULL,
	[Comments] [nvarchar](50) NULL,
	[CategoryId] [int] NULL,
	[UserId] [int] NULL,
	[CreatedOn] [datetime] NOT NULL,
	[UpdatedOn] [datetime] NULL,
	[DeletedOn] [datetime] NULL,
 CONSTRAINT [PK_Events] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  ForeignKey [FK_Events_Category]    Script Date: 05/13/2019 12:39:52 ******/
ALTER TABLE [dbo].[Events]  WITH CHECK ADD  CONSTRAINT [FK_Events_Category] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([Id])
GO
ALTER TABLE [dbo].[Events] CHECK CONSTRAINT [FK_Events_Category]
GO
/****** Object:  ForeignKey [FK_Events_Users]    Script Date: 05/13/2019 12:39:52 ******/
ALTER TABLE [dbo].[Events]  WITH CHECK ADD  CONSTRAINT [FK_Events_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[Events] CHECK CONSTRAINT [FK_Events_Users]
GO
