//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doorway.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Events = new HashSet<Event>();
            this.UserOptions = new HashSet<UserOption>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Name { get; set; }
        public byte[] Picture { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<byte> Role { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<UserOption> UserOptions { get; set; }
    }
}
